#!/usr/bin/python
"""
soma-recorder is a script that creates an ExperimentManager
for managing instances of soma-experiment.

"""
import gobject

import dbus
import dbus.service
import dbus.mainloop.glib
import os
import os.path
import subprocess
from optparse import OptionParser
import soma_apps.recorder

if __name__ == "__main__":

    
    parser = OptionParser()
    parser.add_option("-i", "--soma-ip", dest="somaip", help="The IP address of the Soma hardware")
    parser.add_option("-d", "--dbus", dest="dbus", help="dbus bus to connect to (defaults to Session bus)")
    parser.add_option("-e", "--expdir", dest="expdir", help="directory for experiments")
    parser.add_option("-m", "--mock", action="store_true",
                      dest="mock", help="use mock experiment server (for testing)")
    parser.add_option("-b", "--expbin", dest="expbin",
                      help="The location of the experiment server binary")
    
    (options, args) = parser.parse_args()
    
    dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)

    if options.dbus:
        session_bus = dbus.bus.BusConnection(options.dbus)
        session_bus.address = options.dbus
    else:
        session_bus = dbus.SessionBus()

    if not options.expdir:
        raise Exception("Must specify experiment directory with --expdir")

        
    name = dbus.service.BusName("soma.recording.Manager", session_bus)
    if options.mock:
        ef = soma_apps.recorder.ExperimentFactoryMockup()
    else:
        if options.expbin:
            binname = options.expbin
        else:
            binname = "soma-recording-experiment"
            
        ef = soma_apps.recorder.ExperimentServerFactory(binname)

    if not options.somaip:
        raise Exception("must specify a soma IP")
    
    
    object = soma_apps.recorder.Manager(session_bus, '/manager', options.somaip, options.expdir, ef)
    
    mainloop = gobject.MainLoop()
    mainloop.run()
