
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__dbusrecorderproxy_h__PROXY_MARSHAL_H
#define __dbusxx__dbusrecorderproxy_h__PROXY_MARSHAL_H

#include <dbus-c++/dbus.h>

namespace soma {
namespace recording {

class Recorder
 : public ::DBus::InterfaceProxy
{
public:

    Recorder()
    : ::DBus::InterfaceProxy("soma.recording.Recorder")
    {
        connect_signal(Recorder, experimentavailable, _experimentavailable_stub);
    }

public:

    /* methods exported by this interface,
     * this functions will invoke the corresponding methods on the remote objects
     */
    std::vector< std::string > ListOpenExperiments()
    {
        ::DBus::CallMessage call;
        call.member("ListOpenExperiments");
        ::DBus::Message ret = invoke_method(call);
        ::DBus::MessageIter ri = ret.reader();

        std::vector< std::string > argout;
        ri >> argout;
        return argout;
    }

    std::vector< std::string > ListAvailableExperiments()
    {
        ::DBus::CallMessage call;
        call.member("ListAvailableExperiments");
        ::DBus::Message ret = invoke_method(call);
        ::DBus::MessageIter ri = ret.reader();

        std::vector< std::string > argout;
        ri >> argout;
        return argout;
    }

    void OpenExperiment(const std::string& name)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << name;
        call.member("OpenExperiment");
        ::DBus::Message ret = invoke_method(call);
    }

    void CreateExperiment(const std::string& name)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << name;
        call.member("CreateExperiment");
        ::DBus::Message ret = invoke_method(call);
    }

    std::map< std::string, std::string > GetStatistics()
    {
        ::DBus::CallMessage call;
        call.member("GetStatistics");
        ::DBus::Message ret = invoke_method(call);
        ::DBus::MessageIter ri = ret.reader();

        std::map< std::string, std::string > argout;
        ri >> argout;
        return argout;
    }


public:

    /* signal handlers for this interface
     */
    virtual void experimentavailable(const std::string& objconn) = 0;

private:

    /* unmarshalers (to unpack the DBus message before calling the actual signal handler)
     */
    void _experimentavailable_stub(const ::DBus::SignalMessage &sig)
    {
        ::DBus::MessageIter ri = sig.reader();

        std::string objconn; ri >> objconn;
        experimentavailable(objconn);
    }
};

} } 
namespace soma {
namespace recording {

class ExperimentManager
 : public ::DBus::InterfaceProxy
{
public:

    ExperimentManager()
    : ::DBus::InterfaceProxy("soma.recording.ExperimentManager")
    {
    }

public:

    /* methods exported by this interface,
     * this functions will invoke the corresponding methods on the remote objects
     */
    void RegisterExperiment(const std::string& filename, const std::string& dbusconn)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << filename;
        wi << dbusconn;
        call.member("RegisterExperiment");
        ::DBus::Message ret = invoke_method(call);
    }

    void UnregisterExperiment(const std::string& dbusconn)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << dbusconn;
        call.member("UnregisterExperiment");
        ::DBus::Message ret = invoke_method(call);
    }


public:

    /* signal handlers for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual signal handler)
     */
};

} } 
#endif//__dbusxx__dbusrecorderproxy_h__PROXY_MARSHAL_H
