
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__dbusrecorderadaptor_h__ADAPTOR_MARSHAL_H
#define __dbusxx__dbusrecorderadaptor_h__ADAPTOR_MARSHAL_H

#include <dbus-c++/dbus.h>

namespace soma {
namespace recording {

class Manager_adaptor
: public ::DBus::InterfaceAdaptor
{
public:

    Manager_adaptor()
    : ::DBus::InterfaceAdaptor("soma.recording.Manager")
    {
        register_method(Manager_adaptor, ListOpenExperiments, _ListOpenExperiments_stub);
        register_method(Manager_adaptor, ListAvailableExperiments, _ListAvailableExperiments_stub);
        register_method(Manager_adaptor, OpenExperiment, _OpenExperiment_stub);
        register_method(Manager_adaptor, CreateExperiment, _CreateExperiment_stub);
        register_method(Manager_adaptor, GetStatistics, _GetStatistics_stub);
    }

    ::DBus::IntrospectedInterface *const introspect() const 
    {
        static ::DBus::IntrospectedArgument ListOpenExperiments_args[] = 
        {
            { "results", "as", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument ListAvailableExperiments_args[] = 
        {
            { "results", "as", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument OpenExperiment_args[] = 
        {
            { "name", "s", true },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument CreateExperiment_args[] = 
        {
            { "name", "s", true },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument GetStatistics_args[] = 
        {
            { "stats", "a{ss}", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument experimentavailable_args[] = 
        {
            { "objconn", "s", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedMethod Manager_adaptor_methods[] = 
        {
            { "ListOpenExperiments", ListOpenExperiments_args },
            { "ListAvailableExperiments", ListAvailableExperiments_args },
            { "OpenExperiment", OpenExperiment_args },
            { "CreateExperiment", CreateExperiment_args },
            { "GetStatistics", GetStatistics_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod Manager_adaptor_signals[] = 
        {
            { "experimentavailable", experimentavailable_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty Manager_adaptor_properties[] = 
        {
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface Manager_adaptor_interface = 
        {
            "soma.recording.Manager",
            Manager_adaptor_methods,
            Manager_adaptor_signals,
            Manager_adaptor_properties
        };
        return &Manager_adaptor_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */
    virtual std::vector< std::string > ListOpenExperiments() = 0;
    virtual std::vector< std::string > ListAvailableExperiments() = 0;
    virtual void OpenExperiment(const std::string& name) = 0;
    virtual void CreateExperiment(const std::string& name) = 0;
    virtual std::map< std::string, std::string > GetStatistics() = 0;

public:

    /* signal emitters for this interface
     */
    void experimentavailable(const std::string& arg1)
    {
        ::DBus::SignalMessage sig("experimentavailable");
        ::DBus::MessageIter wi = sig.writer();
        wi << arg1;
        emit_signal(sig);
    }

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
    ::DBus::Message _ListOpenExperiments_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        std::vector< std::string > argout1 = ListOpenExperiments();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _ListAvailableExperiments_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        std::vector< std::string > argout1 = ListAvailableExperiments();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _OpenExperiment_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        std::string argin1; ri >> argin1;
        OpenExperiment(argin1);
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
    ::DBus::Message _CreateExperiment_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        std::string argin1; ri >> argin1;
        CreateExperiment(argin1);
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
    ::DBus::Message _GetStatistics_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        std::map< std::string, std::string > argout1 = GetStatistics();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
};

} } 
namespace soma {
namespace recording {

class ExperimentRegistry_adaptor
: public ::DBus::InterfaceAdaptor
{
public:

    ExperimentRegistry_adaptor()
    : ::DBus::InterfaceAdaptor("soma.recording.ExperimentRegistry")
    {
        register_method(ExperimentRegistry_adaptor, Register, _Register_stub);
        register_method(ExperimentRegistry_adaptor, Unregister, _Unregister_stub);
    }

    ::DBus::IntrospectedInterface *const introspect() const 
    {
        static ::DBus::IntrospectedArgument Register_args[] = 
        {
            { "filename", "s", true },
            { "dbusconn", "s", true },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument Unregister_args[] = 
        {
            { "dbusconn", "s", true },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedMethod ExperimentRegistry_adaptor_methods[] = 
        {
            { "Register", Register_args },
            { "Unregister", Unregister_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod ExperimentRegistry_adaptor_signals[] = 
        {
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty ExperimentRegistry_adaptor_properties[] = 
        {
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface ExperimentRegistry_adaptor_interface = 
        {
            "soma.recording.ExperimentRegistry",
            ExperimentRegistry_adaptor_methods,
            ExperimentRegistry_adaptor_signals,
            ExperimentRegistry_adaptor_properties
        };
        return &ExperimentRegistry_adaptor_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */
    virtual void Register(const std::string& filename, const std::string& dbusconn) = 0;
    virtual void Unregister(const std::string& dbusconn) = 0;

public:

    /* signal emitters for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
    ::DBus::Message _Register_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        std::string argin1; ri >> argin1;
        std::string argin2; ri >> argin2;
        Register(argin1, argin2);
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
    ::DBus::Message _Unregister_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        std::string argin1; ri >> argin1;
        Unregister(argin1);
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
};

} } 
#endif//__dbusxx__dbusrecorderadaptor_h__ADAPTOR_MARSHAL_H
